// B2B.ts

export const EMPLOYMENT_STATUS_OPTIONS = [
    'Employed full-time',
    'Employed part-time',
    'Self-employed full-time',
    'Self-employed part-time',
    'Active military',
    'Inactive military/Veteran',
    'Temporarily unemployed',
    'Full-time homemaker',
    'Retired',
    'Student',
    'Disabled',
    'Unemployed',
    'Prefer not to answer',
  ];
  
  export const EMPLOYEE_SIZE_OPTIONS = [
    '1-10',
    '11-50',
    '51-200',
    '201-500',
    '501-1000',
    '1001-5000',
    '5001-10,000',
    '10,001+',
  ];
  
  export const COMPANY_REVENUE_OPTIONS = [
    'Less than $50,000',
    '$100,000 - $249,999',
    '$250,000 - $499,999',
    '$1 million – less than $5 million',
    '$5 million - less than $10 million',
    '$10 million – less than $25 million',
    '$50 million – less than $75 million',
    '$75 million – less than $100 million',
    '$500 million – less than $1 billion',
    'More than $1 billion',
  ];
  
  export const ROLE_OPTIONS = [
    'Active armed forces/military',
    'Administrative/Clerical',
    'Agricultural worker',
    'Analyst',
    'Applications programmer (e.g app developer)',
    'Architect, engineer or science professional',
    'Assistant or Associate',
    'Builder, general construction worker, bricklayer',
    'Building manager/director',
    'Business Administrator',
    'Buyer/Purchasing Agent',
    'Carpenter or joiner',
    'Chief Information officer (CIO)',
    'C-Level (e.g. CEO, CFO), Owner, Partner, President',
    'Computer network and systems technician',
    'Craftsman/Tradesman',
    'Database designer and administrator',
    'Department Head or Team Lead',
    'Director (Group Director, Sr. Director, Director)',
    'Driver (e.g taxi, bus, van, truck driver)',
    'Facilities manager/director',
    'Faculty/Teaching Staff',
    'Finance manager/director',
    'Financial analyst',
    'Financial and investment adviser',
    'Flooring/tiling/wallpapering/painting technician',
    'Foreman',
    'Forestry or fishery worker',
    'Fraud director/manager',
    'General contractor',
    'Health professional (doctor, nurse, pharmacist)',
    'Health service manager/director',
    'Healthcare technologist/administrator',
    'Help desk technician',
    'Hospitality, retail, other services mgr/director',
    'HR manager',
    'Information technology manager/director',
    'Intern',
    'Laboratory professional',
    'Laborer/Service occupation (maid, miner, waiter)',
    'Legal professional (attorney, paralegal, lawyer)',
    'Manager (Group Manager, Sr. Manager, Manager, Program Manager)',
    'Network administrator',
    'Other IT Architect/consultant',
    'Other non-management staff',
    'Personal care/protective service worker',
    'Plant/machine operator, heavy equipment operator',
    'Plumber or pipe fitter',
    'Product Manager',
    'Production services manager/director',
    'Project Management',
    'Risk Management director/manager',
    'Roofer',
    'Sales Manager',
    'Sales Staff',
    'Salesperson (e.g shop, market salesperson)',
    'Social and cultural professional',
    'Software developer',
    'Stonemason',
    'Supply Manager',
    'Systems administrator',
    'Systems analyst',
    'Technical Staff',
    'Volunteer',
    'Vice President (EVP, SVP, AVP, VP)',
    'Web and multimedia developer',
  ];
  
  export const INDUSTRY_OPTIONS = [
    'Agriculture/Fishing',
    'Military',
    'Banking/Financial',
    'Information Technology/IT',
    'Communications/Information',
    'Construction',
    'Education',
    'Engineering',
    'Government/Public Sector',
    'Healthcare',
    'Legal/Law',
    'Manufacturing',
    'Marketing/Sales',
    'Media/Entertainment',
    'Pharmaceuticals',
    'Retail',
    'Non Profit/Social services',
    'Security',
    'Telecommunications',
    'Transportation',
    'Hospitality/Tourism',
    'Accounting',
    'Advertising',
    'Architecture',
    'Automotive',
    'Aviation',
    'Bio-Tech',
    'Brokerage',
    'Chemicals/Plastics/Rubber',
    'Computer Hardware',
    'Computer Software',
    'Computer Reseller (software/hardware)',
    'Consulting',
    'Consumer Electronics',
    'Consumer Packaged Goods',
    'Energy/Utilities/Oil and Gas',
    'Environmental Services',
    'Fashion/Apparel',
    'Human Resources',
    'Insurance',
    'Internet',
    'Market Research',
    'Personal Services',
    'Printing Publishing',
    'Public Relations',
    'Real Estate/Property',
    'Shipping/Distribution',
    'Carpentry/Electrical installations/Plumbing',
    'Wholesale',
    'Investment management, investment company',
    'Restaurant / Food',
    'Cannabis',
    'Other',
    "I don't work",
    'Prefer not to say',
  ];

  export const DECISION_MAKER_OPTIONS: string[] = [
    'No influence',
    'IT Hardware',
    'IT Software',
    'Printers and Copiers',
    'Financial Department (Accounting Software, Corporate Credit Card)',
    'Human Resources (Employee Benefits, Retirement Programs)',
    'Office Supplies',
    'Printer and Copier Supplies (e.g. Ink)',
    'Corporate Travel Self',
    'Corporate Travel Company',
    'Telecommunications (Mobile)',
    'Telecommunications (Non-Mobile)',
    'Sales/Business Development',
    'Shipping/Mail Services',
    'Operations/Production',
    'Legal Services',
    'Marketing/Advertising',
    'Security Services',
    'Facilities Maintenance and Management',
    'Food Services/Catering',
    'Auto Leasing/Purchasing',
    'IT services or products',
    'Maintenance',
    'Training',
    'Procurement, buying',
    'Office services, moving',
    'Raw materials, primary products',
    'Real estate services',
    'Recruiting new hires',
    'Website Development/Maintenance',
    'IT Infrastructure/Outsourcing, Systems Integration',
    'Data Storage',
    'Virtualization',
    'Internet and Wireless Services',
    'Network products (Routers, LANs, wireless, etc.)',
    'Handhelds (Cell/Smart phones)',
    'Enterprise Applications (ERP, CRM, etc)',
    'Servers',
    'Meeting accommodations',
    'Computer Services, IT Business Solutions',
    'Other Professional Services/Consultants',
  ];
  
  
  // export const b2bQualificationOptions = {
  //   'Employment Status': EMPLOYMENT_STATUS_OPTIONS,
  //   'Employee Size': EMPLOYEE_SIZE_OPTIONS,
  //   'Company Revenue': COMPANY_REVENUE_OPTIONS,
  //   'Role': ROLE_OPTIONS,
  //   'Industry': INDUSTRY_OPTIONS,
  // };