export const GENDER_OPTIONS: string[] = [
  'Male',
  'Female',
  'Intersex/ambiguous',
  'Prefer not to answer'
];

export const EMPLOYMENT_STATUS_OPTIONS: string[] = [
  'Employed full-time',
  'Employed part-time',
  'Self-employed full-time',
  'Self-employed part-time',
  'Active military',
  'Inactive military/Veteran',
  'Temporarily unemployed',
  'Full-time homemaker',
  'Retired',
  'Student',
  'Disabled',
  'Unemployed',
  'Prefer not to answer'
];

export const ETHNICITY_OPTIONS: string[] = [
  'African',
  'African American',
  'Asian',
  'Asian Indian/East Indian',
  'Caucasian/White',
  'Hispanic/Latino',
  'Middle Eastern/Arabic/Persian',
  'Native American/Indigenous',
  'Pacific Islander',
  'Biracial/Multiracial',
  'Other or mixed ethnicities'
];
export const MEDICAL_CONDITION_OPTIONS = [
  'Anemia',
  'Hemophilia A',
  'Hemophilia B',
  'Sickle-cell Disease',
  "Sjogren's syndrome",
  'Von Willebrand Disease',
  "Dupuytren's Contracture",
  'Gout',
  'Osteoarthritis',
  'Osteopena',
  'Osteoporosis',
  'Psoriatic Arthritis',
  'Restless Leg Syndrome',
  'Rheumatoid Arthritis',
  'Cancer Bladder',
  'Cancer Bone',
  'Cancer Brain',
  'Cancer Breast',
  'Cancer Cervical',
  'Cancer Colon',
  'Cancer Head & Neck',
  "Cancer Hodgkin's Lymphoma",
  'Cancer Kidney',
  'Cancer Leukemia',
  'Cancer Liver',
  'Cancer Lung',
  'Cancer Melanoma',
  'Cancer Multiple Myeloma',
  "Cancer Non-Hodgkin's Lymphoma",
  'Cancer Ovarian',
  'Cancer Pancreatic',
  'Cancer Prostate',
  'Cancer Rectal',
  'Cancer Sarcoma',
  'Cancer Skin',
  'Cancer Stomach',
  'Cancer Testicular',
  'Cancer Throat',
  'Cancer Thyroid',
  'Cancer Uterine',
  'Allergies (Digestive)',
  'Celiac Disease',
  "Crohn's Disease",
  'Colitis / Ulcerative Colitis',
  'Gastroesophageal Reflux Disease / GERD',
  'Gallstones',
  'Heartburn',
  'Inflammatory Bowel Disease',
  'Irritable Bowel Syndrome',
  "Cushing's Syndrome",
  'Diabetes',
  'Diabetes Type 1',
  'Diabetes Type 2',
  "Grave's",
  "Hashimoto's thyroiditis / chronic lymphocytic thyroiditis",
  'Hyperthyroidism',
  'Hyperthyroidism (Underactive)',
  'Hypothyroidism',
  'Thyroid Disorders',
  'Cataract',
  'Color Blindness',
  'Glaucoma',
  'Macular Degeneration - Dry',
  'Macular Degeneration - Wet',
  "Amyotrophic Lateral Sclerosis (ALS, Lou Gehrig's Disease)",
  'Down Syndrome',
  'Fragile X Syndrome',
  "Huntington's Disease",
  'Idiopathic Thrombocytopenic Purpura (ITP)',
  "Klinefelter's Syndrome",
  'Muscular Dystrophy',
  'Phenylketonuria (PKU)',
  'Primary Immune Deficiency Disease (PIDD)',
  'Angina',
  'Arrhythmias',
  'Atrial Fibrillation/Valve Replacement',
  'Cardiomyopathy',
  'Congestive Heart Failure',
  'Coronary Artery Disease',
  'Heart Attack',
  'High Blood Pressure',
  'High Cholesterol',
  'Mitral Regurgitation',
  'Mitral Valve Prolapse',
  'Peripheral Artery Disease',
  'Pulmonary Arterial Hypertension (PAH)',
  'Pulmonary Stenosis',
  'Thrombosis / DVT',
  'Genital Herpes',
  'Hepatitis A',
  'Hepatitis B',
  'Hepatitis C',
  'HIV/AIDS',
  'HPV',
  'Lupus',
  'Lyme Disease',
  'Methicillin-resistant Staphylococcus aureus (MRSA)',
  'Incontinence',
  'Interstitial Cystitis',
  'Kidney Failure / Renal Disease',
  'Overactive Bladder',
  'Anxiety / Panic',
  'Attention Deficit Hyperactivity Disorder',
  'Autism',
  'Bipolar Disorder',
  'Borderline Personality Disorder',
  'Depression',
  'Dissociative Identity Disorder',
  'Dysthymia',
  'Eating Disorders',
  'Generalized Anxiety Disorder',
  'Manic-depressive Illness',
  'Obsessive-compulsive Disorder',
  'Post-traumatic Stress Disorder',
  'Schizoaffective',
  'Schizophrenia',
  'Substance Addiction',
  'Benign Prostatic Hyperplasia',
  'Enlarged Prostate',
  'Erectile Dysfunction',
  'Impotence',
  'Incontinence',
  'Low Testosterone',
  'Varicocele',
  "Alzheimer's",
  'Epilepsy',
  'Hearing Loss',
  'Multiple Sclerosis',
  "Parkinson's Disease",
  'Sciatica',
  'Stroke',
  'Ankylosing Spondylitis',
  'Back Pain',
  'Fibromyalgia',
  'Gout',
  'Neuropathy',
  'Headaches/Migraines',
  'Other Pain Condition',
  'Allergies (Respiratory)',
  'Asthma',
  'Chronic Bronchitis',
  'Cystic Fibrosis',
  'Chronic Obstructive Pulmonary Disease',
  'Emphysema',
  'Interstitial Pulmonary Fibrosis',
  'Pulmonary Embolism',
  'Acne',
  'Allergies (Skin)',
  'Alopecia',
  'Eczema',
  'Hyperhidrosis',
  'Psoriasis',
  'Rosacea',
  'Skin lesions and moles',
  'Seborrheic dermatitis',
  'Vitiligo',
  'Insomnia',
  'Narcolepsy',
  'Sleep Apnea',
  'Endometriosis',
  'Fibroids',
  'Infertility',
  'Polycystic Ovary Syndrome',
  'Premenstrual Dysphoric Disorder',
  'Vaginal Atrophy/Dryness',
  'Vulvodynia'
];

export const MEDICAL_CONDITION_GROUP_OPTIONS = [
  'Blood Disorders and Conditions',
  'Bone and Joint Conditions',
  'Cancer',
  'Digestive System Conditions',
  'Endocrine System (incl. Diabetes & Thyroid Conditions)',
  'Eye Conditions',
  'Genetic/Hereditary',
  'Heart Conditions',
  'Immune System (incl. Infectious Diseases)',
  'Kidneys and Urinary System',
  'Mental Health & Wellness',
  "Men's Health",
  'Nervous System Disorders',
  'Pain',
  'Pulmonary / Lung Conditions',
  'Skin Conditions',
  "Women's Health"
];
