export const AGE_GROUP_OPTIONS: string[] = [
    '18-24',
    '25-34',
    '35-44',
    '45-54',
    '55-64',
    '65-74',
    '75+',
  ];
  
  export const GENDER_OPTIONS: string[] = [
    'Male',
    'Female',
    'Intersex/ambiguous',
    'Prefer not to answer',
  ];

  export const GENDER_IDENTITY_OPTIONS: string[] = [
    'Male/Man',
    'Female/Woman',
    'Gender-fluid/Non-binary',
    'Prefer to self-describe',
    'Prefer not to answer',
  ];

  export const HHI_OPTIONS: string[] = [
    'Less than $5,000',
    '$10,000 to $14,999',
    '$15,000 to $19,999',
    '$20,000 to $24,999',
    '$25,000 to $29,999',
    '$30,000 to $34,999',
    '$35,000 to $39,999',
    '$40,000 to $44,999',
    '$45,000 to $49,999',
    '$50,000 to $54,999',
    '$55,000 to $59,999',
    '$60,000 to $64,999',
    '$65,000 to $69,999',
    '$70,000 to $74,999',
    '$75,000 to $79,999',
    '$80,000 to $84,999',
    '$85,000 to $89,999',
    '$90,000 to $94,999',
    '$95,000 to $99,999',
    '$100,000 to $124,999',
    '$125,000 to $149,999',
    '$150,000 to $174,999',
    '$175,000 to $199,999',
    '$200,000 to $249,999',
    '$250,000 and above',
    'Prefer not to answer',
  ];
  
  export const EMPLOYMENT_STATUS_OPTIONS: string[] = [
    'Employed full-time',
    'Employed part-time',
    'Self-employed full-time',
    'Self-employed part-time',
    'Active military',
    'Inactive military/Veteran',
    'Temporarily unemployed',
    'Full-time homemaker',
    'Retired',
    'Student',
    'Disabled',
    'Unemployed',
    'Prefer not to answer',
  ];
  
  export const EDUCATION_OPTIONS: string[] = [
    'Trade School',
    '11th Grade or Lower',
    'High School Graduate',
    'Some College',
    'Associates Degree',
    'Bachelors Degree',
    'Masters Degree',
    'Doctoral Degree',
  ];
  
  export const ETHNICITY_OPTIONS: string[] = [
    'African',
    'African American',
    'Asian',
    'Asian Indian/East Indian',
    'Caucasian/White',
    'Hispanic/Latino',
    'Middle Eastern/Arabic/Persian',
    'Native American/Indigenous',
    'Pacific Islander',
    'Biracial/Multiracial',
    'Other or mixed ethnicities',
  ];

  export const PARENTAL_STATUS_OPTIONS: string[] = [
    'Currently pregnant/expecting a child within the next 9 months',
    'Children over the age of 18 living in the household',
    'Children under the age of 18 living in the household',
    'No children living in the household',
  ];
  
  export const HOUSEHOLD_DECISION_MAKER_OPTIONS: string[] = [
    'Joint household decision maker',
    'Primary household decision maker',
    'Someone else makes household decisions',
  ];
  
  export const VEHICLE_TYPE_OPTIONS: string[] = [
    'Sedan',
    'Hatchback',
    'SUV (Sport Utility Vehicle)',
    'Crossover',
    'Pickup truck',
    'Van',
    'Minivan',
    'Coupe',
    'Convertible',
    'Sports car',
    'Luxury car',
    'Station wagon',
    'Electric vehicle',
    'Hybrid vehicle',
    'Off-road vehicle',
    'Motorcycle',
    'Moped',
    'Scooter',
    'Bicycle with motor (ebike)',
    'RV (Recreational Vehicle)',
    'Trailer',
  ];
  
  export const AUTO_MAKE_OPTIONS: string[] = [
    'Acura',
    'Alfa Romeo',
    'Aston Martin',
    'Audi',
    'Bentley',
    'BMW',
    'Buick',
    'Cadillac',
    'Chevrolet',
    'Chrysler',
    'Dodge',
    'Ferrari',
    'Fiat',
    'Ford',
    'Genesis',
    'GMC',
    'Honda',
    'Hyundai',
    'Infiniti',
    'Jaguar',
    'Jeep',
    'Kia',
    'Lamborghini',
    'Land Rover',
    'Lexus',
    'Lincoln',
    'Lotus',
    'Maserati',
    'Mazda',
    'McLaren',
    'Mercedes-Benz',
    'Mini',
    'Mitsubishi',
    'Nissan',
    'Pagani',
    'Polestar',
    'Porsche',
    'Ram',
    'Rolls-Royce',
    'Subaru',
    'Tesla',
    'Toyota',
    'Volkswagen',
    'Volvo',
  ];
  
  export const SMOKER_TYPE_OPTIONS: string[] = [
    'Roll your own tobacco',
    'Snus',
    'Moist smokeless tobacco',
    'Pipe',
    'Chewing Tobacco',
    'Cigarillos',
    'Cigars',
    'E-cigarettes',
    'Cigarettes',
    'Cannabis',
  ];
  
  export const GAMERS_GAME_TYPE_OPTIONS: string[] = [
    'Action-Adventure Games',
    'First-Person Shooter Games',
    'Platform Games',
    'Role-Playing Games (RPGs)',
    'Flight Simulation Games',
    'Strategy Games',
    'Sports Games',
    'Racing Games',
    'Fighting Games',
    'Puzzle Games',
    'Stealth Games',
    'Educational Games',
    'Music and Dance Games',
    'Casual Games',
    'Massive Multiplayer Online (MMO) Games',
    'Virtual Reality (VR) Games',
    'Augmented Reality (AR) Games',
    'Survival Games',
    'Horror Games',
    'Sandbox Games',
    'Tower Defense Games',
    'Tactical Shooter Games',
    'Life Simulation Games',
    'City-Building Games',
    'Real-Time Strategy (RTS) Games',
    'Turn-Based Strategy (TBS) Games',
    'Party Games',
    'Card Games',
    'Trivia Games',
    'Does not play video games',
  ];
  
  export const PET_TYPE_OPTIONS: string[] = [
    'Dogs',
    'Cats',
    'Fish',
    'Birds',
    'Reptiles',
    'Rodents',
    'Rabbits',
    'Ferrets',
    'Guinea Pigs',
    'Hamsters',
    'Chinchillas',
    'Hedgehogs',
    'Amphibians',
    'Insects',
    'Spiders',
    'Snakes',
    'Turtles',
    'Lizards',
    'Miniature Pigs',
    'Crustaceans',
    'Arthropods',
    'Farm Animals (e.g. Chickens, Cows, Horses, Goats, etc.)',
  ];
  
  export const BIG_TICKET_PURCHASES_OPTIONS: string[] = [
    'Real estate',
    'Vehicles',
    'Appliances',
    'Electronics',
    'Jewelry',
    'Furniture',
    'Home renovation projects',
    'Education',
    'Travel',
  ];
  
  export const SMART_HOME_DEVICES_OPTIONS: string[] = [
    'Smart Speakers',
    'Home Smart Displays',
    'Smart Thermostats',
    'Smart Watches',
    'Smart Doorbell/Cameras',
    'Smart In-home Pet Cameras',
    'Smart Home Security Systems',
    '“Robotic” home cleaning devices',
    'Connected exercise equipment',
  ];
  

  // export const consumerQualificationOptions = {
  //   'Age Group': AGE_GROUP_OPTIONS,
  //   'Gender: Sex assigned at birth': GENDER_OPTIONS,
  //   'HHI': HHI_OPTIONS,
  //   'Employment Status': EMPLOYMENT_STATUS_OPTIONS,
  //   'Education': EDUCATION_OPTIONS,
  //   'Ethnicity': ETHNICITY_OPTIONS,
  //   // Add more qualifications and their corresponding options arrays as needed
  // };