export const HEALTHCARE_ROLE_OPTIONS = [
    'Hospital Executive, Director or Manager',
    'Managed Care Executive',
    'Pharmacist',
    'Physician',
    'Nurse',
    'Physician Assistant',
    'Researcher',
    'Dentist',
    'Allied Health Professional (OT, PT, LMT, SLP, etc.)',
    'Healthcare Support Staff (Scheduling, Billing, Phlebotomy, Nursing Assistant, Hospital Tech, etc.)',
    'Medical Student',
    'Nursing Student',
    'Healthcare Administration',
    'Other , Please specify',
    'I do not have a role in healthcare',
  ];
  
  export const PRACTICE_SETTING_OPTIONS = [
    'Adult Day Care / Adult Nursing Facility',
    'Clinic - Free standing',
    'Clinic - Hospital Based',
    'Community Center',
    'Dialysis Center',
    'Government Facility',
    'Home Health',
    'Hospice Facility',
    'Hospital (ER)',
    'Hospital (General)',
    'Hospital (Inpatient)',
    'Hospital (Outpatient)',
    'Infusion Center',
    'Long term acute care / Rehab facility',
    'Managed Care Organization / HMO',
    'Military / Veterans Administration',
    'Nursing Home / Long Term Care/Skilled Nursing Facility',
    'Office Based Practice',
    'Outpatient Surgical Center',
    'Private Home',
    'School / College / University',
    'Senior Living',
    'Other',
  ];
  
  export const PRIMARY_SPECIALTY_OPTIONS = [
    'Abdominal Radiology',
    'Abdominal Surgery',
    'Addiction Medicine',
    'Addiction Psychiatry',
    'Adolescent Medicine - Internal Medicine',
    'Adolescent Medicine - Pediatrics',
    'Adolescent Medicine - FM/GP',
    'Adult Reconstructive Orthopedics',
    'Aerospace Medicine',
    'Allergy',
    'Allergy/Immunology',
    'Anatomic Pathology',
    'Anatomic/Clinical Pathology',
    'Anesthesiology',
    'Bloodbanking/Transfusion Medicine',
    'Cardiac Electrophysiology',
    'Cardiothoracic Radiology',
    'Cardiovascular Diseases',
    'Chemical Pathology',
    'Child & Adolescent Psychiatry',
    'Child Neurology',
    'Clinical & Lab Derm Immunology',
    'Clinical Biochemical Genetics',
    'Clinical Cytogenetics',
    'Clinical Genetics',
    'Clinical Lab Immunology & Allergy',
    'Clinical Molecular Genetics',
    'Clinical Neurophysiology',
    'Clinical Pathology',
    'Clinical Pharmacology',
    'Clinical/Laboratory  Immunology',
    'Colon & Rectal Surgery',
    'Cosmetic Surgery',
    'Craniofacial Surgery',
    'Critical Care Medicine - Anesthesiology',
    'Critical Care Medicine - IM',
    'Cytopathology',
    'Dermatologic Surgery',
    'Dermatology',
    'Dermatopathology - Dermatology',
    'Dermatopathology - Pathology',
    'Developmental-Behavioral Pediatrics',
    'Diabetes',
    'Diagnostic Radiology',
    'Emergency Medicine',
    'Endocrinology',
    'Epidemiology',
    'Facial Plastic Surgery',
    'Family Practice',
    'FAMILY/GENERAL  PRACTICE',
    'Foot & Ankle Orthopedics',
    'Forensic Pathology',
    'Forensic Psychiatry',
    'Gastroenterology',
    'General Practice',
    'General Preventive Medicine',
    'General Surgery',
    'Geriatric Medicine-FP',
    'Geriatric Medicine-IM',
    'Geriatric Psychiatry',
    'GERIATRICS',
    'Gynecological Oncology',
    'Gynecology',
    'Hand Surgery',
    'Head & Neck Surgery',
    'Hematology - IM',
    'Hematology - Pathology',
    'Hematology/Oncology',
    'Hepatology',
    'Hospitalist',
    'IM/Pediatrics - IM',
    'IM/Pediatrics - Pediatrics',
    'Immunology',
    'Infectious Disease',
    'Internal Medicine',
    'Interventional Cardiology',
    'Legal Medicine',
    'Maternal & Fetal Medicine',
    'Medical Genetics',
    'Medical Management',
    'Medical Microbiology',
    'Medical Oncology',
    'Medical Toxicology - Emergency Medicine',
    'Medical Toxicology - Preventative Medicine',
    'Molecular Genetic Pathology - Medical Genetics',
    'Molecular Genetic Pathology - Pathology',
    'Musculoskeletal Oncology',
    'Musculoskeletal Radiology',
    'Neonatal-Perinatal Medicine',
    'Nephrology',
    'Neurodevelopmental Disabilities - Neurology',
    'Neurodevelopmental Disabilities - Pediatrics',
    'Neurological Surgery',
    'Neurology',
    'Neurology/Diag Rad/Neuroradiology - Neurology',
    'Neurology/DiagRad/Neuroradiology - Radiology',
    'Neuropathology',
    'Neuroradiology',
    'Nuclear Cardiology',
    'Nuclear Medicine',
    'Nuclear Radiology',
    'Nutrition',
    'Obstetric Critical Care Medicine',
    'Obstetrics',
    'Obstetrics & Gynecology',
    'Occupational Medicine',
    'Ophthalmology',
    'Oral & Maxillofacial Surgery',
    'Orthopedic Surgery',
    'Orthopedic Trauma Surgery',
    'Osteopathic  Manipulative Medicine',
    'Other Specialty',
    'Other, Specify',
    'Otolaryngology',
    'Otology/Neurotology',
    'Pain Management',
    'Pain Medicine',
    'Palliative Medicine',
    'Pediatric Allergy',
    'Pediatric Anesthesiology',
    'Pediatric Cardiology',
    'Pediatric Cardiothoracic Surgery',
    'Pediatric Clinical & Lab Immunology',
    'Pediatric Critical Care Medicine',
    'Pediatric Dermatology',
    'Pediatric Emergency Medicine - Emergency Medicine',
    'Pediatric Emergency Medicine - Pediatrics',
    'Pediatric Endocrinology',
    'Pediatric Gastroenterology',
    'Pediatric Infectious Disease',
    'Pediatric Medical Toxicology',
    'Pediatric Nephrology',
    'Pediatric Ophthalmology',
    'Pediatric Orthopedics',
    'Pediatric Otolaryngology',
    'Pediatric Pathology',
    'Pediatric Pulmonology',
    'Pediatric Radiology',
    'Pediatric Rehabilitation Medicine',
    'Pediatric Rheumatology',
    'Pediatric Surgery',
    'Pediatric Surgery- Neurological',
    'Pediatric  Hematology/Oncology',
    'Pediatrics',
    'Pharmaceutical Medicine',
    'Physical Medicine & Rehabilitation',
    'PLASTIC SURGERY',
    'Plastic Surgery',
    'Plastic Surgery within Head & Neck',
    'Proctology',
    'Psychiatry',
    'Psychoanalysis',
    'Public Health & General Prev. Med',
    'Pulmonary Critical Care Medicine',
    'Pulmonary Disease',
    'Radiation Oncology',
    'Radiological Physics',
    'Radiology',
    'Reproductive Endocrinology',
    'Rheumatology',
    'Selective Pathology',
    'Sleep Medicine',
    'Spinal Cord Injury',
    'Spine Surgery',
    'Sports Medicine- (PM & R)',
    'Sports Medicine- EM',
    'Sports Medicine- FP',
    'Sports Medicine- IM',
    'Sports Medicine- Orthopedics',
    'Sports Medicine- Pediatric',
    'Surgical Critical Care',
    'Surgical Oncology',
    'Thoracic Surgery',
    'Transplant Surgery',
    'Trauma Surgery',
    'Undersea & Hyperbaric Medicine',
    'Urology',
    'Vascular Medicine',
    'Vascular Neurology',
    'Vascular Surgery',
    'Vascular/Interventional Radiology',
  ];
  
  export const SPECIALTY_AREA_OPTIONS = [
    'ALLERGY/IMMUNOLOGY',
    'ANESTHESIOLOGY',
    'CARDIOLOGY',
    'DERMATOLOGY',
    'EMERGENCY MEDICINE',
    'ENDOCRINOLOGY/DIABETES/METABOLISM',
    'FAMILY/GENERAL PRACTICE',
    'GERIATRICS',
    'INTERNAL MEDICINE',
    'MEDICAL GENETICS',
    'NEUROLOGICAL SURGERY',
    'NEUROLOGY',
    'OBSTETRICS/GYNECOLOGY',
    'ONCOLOGY (CANCER)',
    'OPHTHALMOLOGY',
    'ORTHOPEDICS',
    'OTHER',
  ];

  // export const healthcareQualificationOptions = {
  //   'Healthcare Role': HEALTHCARE_ROLE_OPTIONS,
  //   'Practice Setting': PRACTICE_SETTING_OPTIONS,
  //   'Primary Specialty': PRIMARY_SPECIALTY_OPTIONS,
  //   'Specialty Area': SPECIALTY_AREA_OPTIONS,
  //   // Add more qualifications and their corresponding options arrays as needed
  // };
  